author: 'verkstedt GmbH <info@verkstedt.com>'
name: jira-integration
description: GitHub Action to move Jira tickets based on PR status
branding:
  color: yellow
  icon: anchor
inputs:
  github-token:
    description: 'Github token, https://docs.github.com/en/actions/reference/authentication-in-a-workflow'
    required: true
  jira-domain:
    description: 'Jira domain, e.g. example.atlassian.net'
    required: true
  jira-user:
    description: 'Email address of the Jira user'
    required: true
  jira-api-token:
    description: 'Jira API key, get it on <https://id.atlassian.com/manage-profile/security/api-tokens>. Note that user whose API token is used, will “touch” all of the issues, so it’s best to create a dedicated user for this sort of things.'
    required: true
  jira-status-pr-draft:
    description: 'Name of the status to transition issue to when PR is in draft'
    required: false
  jira-status-pr-ready:
    description: 'Name of the status to transition issue to when PR is ready to review'
    required: false
  jira-status-pr-merged:
    description: 'Name of the status to transition issue to when PR is merged'
    required: false
runs:
  using: node20
  main: 'dist/index.mjs'
